default:
  image: snazzybucket/idris2:v0.3.0-588-g2f66f3e0
  # get the desired suffix by `git describe --tags`

stages:
  - lib-build
  - lib-test
  - example-build
  - example-test
  - check-latest

build-deptycheck-lib:
  stage: lib-build
  script:
    - make deptycheck

test-deptycheck-lib:
  stage: lib-test
  script:
    - make test-deptycheck

build-pil:
  stage: example-build
  script:
    - make pil

test-pil:
  stage: example-test
  script:
    - make test-pil

# TODO To make testing on the latest compiler version symmetric to the rest.
#      Something like matrix with the `image` and `allow_failure` alternating.
test-latest:
  stage: check-latest
  image: snazzybucket/idris2:latest
  allow_failure: true
  script:
    - make test-all
