variables:
  GIT_SUBMODULE_STRATEGY: recursive
  IDRIS_VERSION_FILE: .idris-version # should contain the result of `git describe --tags`

read-idris-ver:
  stage: .pre
  script:
    - sed 's/^/preferred_idris=/' < "${IDRIS_VERSION_FILE}" > idris.env
  artifacts:
    reports:
      dotenv: idris.env

.depends-on-idris:
  parallel:
    matrix:
      - IDRIS2_TAG:
        - ${preferred_idris}
        - latest
  image: snazzybucket/idris2:${IDRIS2_TAG}
  rules:
    - if: $IDRIS2_TAG == "latest"
      allow_failure: true
    - if: $IDRIS2_TAG

stages:
  - thirdparties:build
  - lint
  - deptycheck:build
  - deptycheck:test:lib
  - deptycheck:test:derive
  - pil:build
  - pil:test

# TODO to cache the results of builds to those jobs that have `needs` for them (transitively).

# TODO to find a way to not to repeat `read-idris-ver` in `needs` for every job that extends `.depends-on-idris`.

thirdparties:build:
  extends: .depends-on-idris
  stage: thirdparties:build
  needs:
    - read-idris-ver
  script:
    - make thirdparties

deptycheck:build:
  extends: .depends-on-idris
  stage: deptycheck:build
  needs:
    - read-idris-ver
    - thirdparties:build
  script:
    - make deptycheck

deptycheck:test:lib:
  extends: .depends-on-idris
  stage: deptycheck:test:lib
  needs:
    - read-idris-ver
    - deptycheck:build
  script:
    - make test-deptycheck only=lib/ INTERACTIVE="--color"

deptycheck:test:derive:
  extends: .depends-on-idris
  stage: deptycheck:test:derive
  needs:
    - read-idris-ver
    - deptycheck:build
    - deptycheck:test:lib
  script:
    - "thr=$(( `nproc` / 2 ))"
    - "thr=$(( thr < 2 ? 2 : thr ))"
    - make test-deptycheck only=gen-derivation/ INTERACTIVE="--color" threads=$thr

pil:build:
  extends: .depends-on-idris
  stage: pil:build
  needs:
    - read-idris-ver
    - deptycheck:build
  script:
    - make pil

pil:test:
  extends: .depends-on-idris
  stage: pil:test
  needs:
    - read-idris-ver
    - pil:build
    - deptycheck:test:lib
  script:
    - make test-pil INTERACTIVE="--color"

include:
  - remote: 'https://jobs.r2devops.io/latest/super_linter.yml'

super_linter:
  stage: lint
  needs: []
  variables:
    FILTER_REGEX_EXCLUDE: ".*/thirdparty/.*"
