.depends-on-idris:
  parallel:
    matrix:
      - IDRIS2_TAG:
        - v0.4.0-252-gb03395de
        # get the desired suffix by `git describe --tags`
        - latest
  image: snazzybucket/idris2:${IDRIS2_TAG}

stages:
  - lint
  - build-lib
  - test-lib
  - build-example
  - test-example

build-deptycheck-lib:
  extends: .depends-on-idris
  stage: build-lib
  script:
    - make deptycheck

test-deptycheck-lib:
  extends: .depends-on-idris
  stage: test-lib
  script:
    - make test-deptycheck

build-pil:
  extends: .depends-on-idris
  stage: build-example
  script:
    - make pil

test-pil:
  extends: .depends-on-idris
  stage: test-example
  script:
    - make test-pil

include:
  - remote: 'https://jobs.r2devops.io/latest/super_linter.yml'

super_linter:
  stage: lint
