.default:
  parallel:
    matrix:
      - IDRIS2_TAG:
        - v0.3.0-588-g2f66f3e0
        # get the desired suffix by `git describe --tags`
        - latest
  image: snazzybucket/idris2:${IDRIS2_TAG}

stages:
  - build-lib
  - test-lib
  - build-example
  - test-example

build-deptycheck-lib:
  extends: .default
  stage: build-lib
  script:
    - make deptycheck

test-deptycheck-lib:
  extends: .default
  stage: test-lib
  script:
    - make test-deptycheck

build-pil:
  extends: .default
  stage: build-example
  script:
    - make pil

test-pil:
  extends: .default
  stage: test-example
  script:
    - make test-pil
