variables:
  GIT_SUBMODULE_STRATEGY: recursive

.depends-on-idris:
  parallel:
    matrix:
      - IDRIS2_TAG:
        - v0.5.1-27-g1ebe204c
        # get the desired suffix by `git describe --tags`
        - latest
  image: snazzybucket/idris2:${IDRIS2_TAG}
  rules:
    - if: $IDRIS2_TAG == "latest"
      allow_failure: true
    - if: $IDRIS2_TAG

stages:
  - thirdparties:build
  - lint
  - deptycheck:build
  - deptycheck:test:lib
  - deptycheck:test:derive
  - pil:build
  - pil:test

# TODO to cache the results of builds to those jobs that have `needs` for them (transitively).

thirdparties:build:
  extends: .depends-on-idris
  stage: thirdparties:build
  needs: []
  script:
    - make thirdparties

deptycheck:build:
  extends: .depends-on-idris
  stage: deptycheck:build
  needs:
    - thirdparties:build
  script:
    - make deptycheck

deptycheck:test:lib:
  extends: .depends-on-idris
  stage: deptycheck:test:lib
  needs:
    - deptycheck:build
  script:
    - find tests/ -maxdepth 1 -mindepth 1 -type d ! -name gen-derivation | sed 's|^tests/||' | while read r; do
        make test-deptycheck only="$r";
      done

deptycheck:test:derive:
  extends: .depends-on-idris
  stage: deptycheck:test:derive
  needs:
    - deptycheck:build
    - deptycheck:test:lib
  script:
    - make test-deptycheck only=gen-derivation/

pil:build:
  extends: .depends-on-idris
  stage: pil:build
  needs:
    - deptycheck:build
  script:
    - make pil

pil:test:
  extends: .depends-on-idris
  stage: pil:test
  needs:
    - pil:build
    - deptycheck:test:lib
  script:
    - make test-pil

include:
  - remote: 'https://jobs.r2devops.io/latest/super_linter.yml'

super_linter:
  stage: lint
  needs: []
  variables:
    FILTER_REGEX_EXCLUDE: ".*/thirdparty/.*"
