################
### Settings ###
################

[install]
whitelist = [ "deptycheck-docs" ]

##################
### DepTyCheck ###
##################

[custom.all.deptycheck]
type = "local"
path = "."
ipkg = "deptycheck.ipkg"
test = "tests/tests.ipkg"

[custom.all.docs]
type = "local"
path = "docs"
ipkg = "docs.ipkg"

################
### Examples ###
################

[custom.all.pil]
type = "local"
path = "examples/pil"
ipkg = "pil.ipkg"
test = "tests/tests.ipkg"

[custom.all.sorted-trees]
type = "local"
path = "examples/sorted-trees"
ipkg = "sorted-trees.ipkg"
test = "tests/tests.ipkg"

####################
### Thirdparties ###
####################

[custom.all.elab-util]
type   = "git"
url    = "https://github.com/buzden/idris2-elab-util"
commit = "6ff9878208940a9f8074f9030e272f4ca176d64f"
ipkg   = "elab-util.ipkg"
